<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="InvalidCredentialException.xml" source-language="en-US" target-language="pt-BR">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac552cbc40e967191f7946b3f734dbbcd7a0264806a.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">52cbc40e967191f7946b3f734dbbcd7a0264806a</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netcore-2.1,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,netstandard-2.0,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Security.Authentication.InvalidCredentialException">
          <source>The exception that is thrown when authentication fails for an authentication stream and cannot be retried.</source>
          <target state="translated">A exceção que é gerada quando a autenticação falha para um fluxo de autenticação e não pode ser recuperada.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Security.Authentication.InvalidCredentialException">
          <source>The <ph id="ph1">&lt;xref:System.Net.Security.NegotiateStream&gt;</ph> class throws this exception when authentication fails.</source>
          <target state="translated">O <ph id="ph1">&lt;xref:System.Net.Security.NegotiateStream&gt;</ph> classe lança esta exceção quando a autenticação falhará.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Security.Authentication.InvalidCredentialException">
          <source>This exception indicates that the underlying stream isn't in a valid state and that you can't retry the authentication using the <ph id="ph1">&lt;xref:System.Net.Security.NegotiateStream&gt;</ph> instance.</source>
          <target state="translated">Esta exceção indica que o fluxo subjacente não está em um estado válido e que não é possível repetir a autenticação usando o <ph id="ph1">&lt;xref:System.Net.Security.NegotiateStream&gt;</ph> instância.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Security.Authentication.InvalidCredentialException">
          <source>If you retry the authentication, an <ph id="ph1">&lt;xref:System.Security.Authentication.AuthenticationException&gt;</ph> is thrown instead of the <ph id="ph2">&lt;xref:System.Security.Authentication.InvalidCredentialException&gt;</ph>.</source>
          <target state="translated">Se você tentar novamente a autenticação, um <ph id="ph1">&lt;xref:System.Security.Authentication.AuthenticationException&gt;</ph> é gerada em vez do <ph id="ph2">&lt;xref:System.Security.Authentication.InvalidCredentialException&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" uid="T:System.Security.Authentication.InvalidCredentialException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> class.</source>
          <target state="translated">Inicializa uma nova instância da classe <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> class with no message.</source>
          <target state="translated">Inicializa uma nova instância da classe <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> sem mensagens.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor">
          <source>This constructor does nothing.</source>
          <target state="translated">Este construtor não fará nada.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.String)">
          <source>A <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph> that describes the authentication failure.</source>
          <target state="translated">Um <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph> que descreve a falha de autenticação.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> class with the specified message.</source>
          <target state="translated">Inicializa uma nova instância da classe <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> com a mensagem especificada.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.String)">
          <source>This constructor initializes the <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> property with the text in the <ph id="ph2">`message`</ph> parameter.</source>
          <target state="translated">Este construtor inicializa o <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> propriedade com o texto de <ph id="ph2">`message`</ph> parâmetro.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.String)">
          <source>The <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property is set to <ph id="ph2">`null`</ph>.</source>
          <target state="translated">A propriedade <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> é definida como <ph id="ph2">`null`</ph>.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>A <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> instance that contains the information required to deserialize the new <ph id="ph2">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> instance.</source>
          <target state="translated">Uma instância <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> que contém as informações necessárias para desserializar a nova instância <ph id="ph2">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>A <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> instance.</source>
          <target state="translated">Uma instância de <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> class from the specified instances of the <ph id="ph2">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> and <ph id="ph3">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> classes.</source>
          <target state="translated">Inicializa uma nova instância da classe <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> das instâncias especificadas das classes <ph id="ph2">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> e <ph id="ph3">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.String,System.Exception)">
          <source>A <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph> that describes the authentication failure.</source>
          <target state="translated">Um <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph> que descreve a falha de autenticação.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Exception" /&gt;</ph> that is the cause of the current exception.</source>
          <target state="translated">A <ph id="ph1">&lt;see cref="T:System.Exception" /&gt;</ph> que é a causa da exceção atual.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> class with the specified message and inner exception.</source>
          <target state="translated">Inicializa uma nova instância da classe <ph id="ph1">&lt;see cref="T:System.Security.Authentication.InvalidCredentialException" /&gt;</ph> com a mensagem e exceção interna especificadas.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Security.Authentication.InvalidCredentialException.#ctor(System.String,System.Exception)">
          <source>This constructor initializes the <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> property with the text in the <ph id="ph2">`message`</ph> parameter and initializes the <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property with the <ph id="ph4">`innerException`</ph> parameter value.</source>
          <target state="translated">Este construtor inicializa o <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> propriedade com o texto no <ph id="ph2">`message`</ph> parâmetro e inicializa o <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> propriedade com o <ph id="ph4">`innerException`</ph> o valor do parâmetro.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>